<?php
namespace app\components;

use yii\base\Component;

class Cart extends Component
{

    public function put($name, $price, $count)
    {
        $_SESSION['MyCart'][] = [$name, $price, $count];
    }

    public function getElements()
    {
        return $_SESSION['MyCart'];
    }

    public function getCost()
    {
        $cost = 0;
        foreach ($_SESSION['MyCart'] as $item){
            $cost += $item[1]*$item[2];
        }
        return $cost;
    }

    
    /**
     * @param int $a
     * @return int
     */
    public function getCount()
    {
        $count = 0;
        foreach ($_SESSION['MyCart'] as $item){
            $count += $item[2];
        }
        return $count;
    }

    public function truncate()
    {
        unset($_SESSION['MyCart']);
        return true;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!isset($_SESSION['MyCart'])){
            $_SESSION['MyCart'] = [];
        }
    }

}